# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "foreverfei"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Image Restoration": 
        filters: ["Image Restoration", "Image Enhancement"]
    "ALL-IN-ONE Image Restoration":
        filters: ["all-in-one", "all-in-one Image Restoration", "multi-degraded image restoration"]
    "3DGAS":
        filters: ["3DGAS","2DGAS", "NERF"]
    "LLM":
        filters: ["Keypoint Detection", "Feature Descriptor"]
    "IQA":
        filters: ["IQA", "No-IQA", 
                  "image iqa", "video iqa"]
    "Difffusion":
        filters: ["diffusion image restoration"]
